apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "mychart.labels" . }}

data:
  myvalue: "Hello World"
  {{- $relname := .Release.Name }}
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  release: {{ $relname }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: "true"
  {{- end }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end}}
  sizes: |-
    {{- range tuple "small" "midum" "large" }}
    - {{ . }}
    {{- end }}
    {{- include "mychart.app" . | indent 2}}
  test1conf: |-
  {{ (.Files.Glob "conf/test1.conf").AsConfig | indent 2 }}
  token: |-
  {{ (.Files.Glob "conf/token.txt").AsConfig | b64enc | indent 2 }}
  test2conf: |-
  {{ (.Files.Glob "conf/test2.conf").AsConfig | indent 2 }}
  filelines: {{ range .Files.Lines "conf/test2.conf" }}
    {{ . }}{{ end }}
  dessert: |-
  {{- range .Values.dessert }}
  - {{ . }}
  {{- end }}
